# Generated by Django 3.0.6 on 2020-05-31 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cpf_cnpj',
        ),
        migrations.AddField(
            model_name='profile',
            name='answered_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
